name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  
  cypress-tests-cadastro:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run end-to-end tests on tablet viewprt 🧪
        uses: cypress-io/github-action@v3
        with:
          node-version: 16
          command: npm run test:cadastro
      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v2.2.4
        with:
          path: cypress/videos
          
 
          
  
          
 
          
  
